name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - run: |
            rustup toolchain install stable
            rustup toolchain list
            cargo --version
            cargo clippy --version
      - run: cargo fmt --all --check
      - run: cargo test --workspace --all-targets --all-features
      - run: cargo clippy --workspace --all-targets --all-features